# Generated by Django 3.0.3 on 2020-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'unselected'), (1, 'male'), (2, 'female')], default=0),
        ),
    ]
