# Generated by Django 3.0.3 on 2020-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_auto_20200222_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('times', models.ManyToManyField(to='cinema_app.Hour')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.DeleteModel(
            name='SessionTime',
        ),
        migrations.AlterField(
            model_name='session',
            name='times',
            field=models.ManyToManyField(to='cinema_app.SessionDate'),
        ),
    ]
