# Generated by Django 3.0.3 on 2020-02-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_auto_20200222_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='times',
            new_name='dates',
        ),
        migrations.AddField(
            model_name='hall',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema_app.HallType'),
            preserve_default=False,
        ),
    ]
