# Generated by Django 3.0.3 on 2020-02-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_auto_20200222_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
