# Generated by Django 3.0.3 on 2020-02-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_hall_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='slug',
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
