# Generated by Django 3.0.3 on 2020-03-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0013_auto_20200226_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.City', unique=True),
        ),
    ]
