# Generated by Django 3.0.3 on 2020-03-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0016_auto_20200320_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='format',
            new_name='formats',
        ),
    ]
