# Generated by Django 3.0.3 on 2020-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0017_auto_20200325_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='now_playing',
            field=models.BooleanField(default=False),
        ),
    ]
