# Generated by Django 3.0.3 on 2020-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0018_auto_20200326_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='now_playing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
